### ISSUE TITLE
Error after claiming the robot

### ISSUE THREAD

**Issue by zhaozhongch** [heuristicus/spot_ros#43]
After I run the command
```
roslaunch spot_driver driver.launch 
```
I can connect the spot normally and control it through different commands such as sit, stand, velocity.
However, after a few seconds, the terminal will show an error. I can still control the robot, just the error bothers me.
```
Traceback (most recent call last):
  File "/home/zhaozhong/spot/spot_ws/src/spot_ros/spot_driver/scripts/spot_ros", line 7, in <module>
    SR.main()
  File "/home/zhaozhong/spot/spot_ws/src/spot_ros/spot_driver/src/spot_driver/spot_ros.py", line 586, in main
    self.spot_wrapper.updateTasks()
  File "/home/zhaozhong/spot/spot_ws/src/spot_ros/spot_driver/src/spot_driver/spot_wrapper.py", line 402, in updateTasks
    self._async_tasks.update()
  File "/home/zhaozhong/.local/lib/python3.6/site-packages/bosdyn/client/async_tasks.py", line 39, in update
    task.update()
  File "/home/zhaozhong/.local/lib/python3.6/site-packages/bosdyn/client/async_tasks.py", line 90, in update
    self._handle_result(self._future.result())
  File "/home/zhaozhong/.local/lib/python3.6/site-packages/bosdyn/client/common.py", line 458, in result
    raise error
```
The spot software is the latest version

**Comment by heuristicus** [comment]
Do you get any specific output from the error? It's raising an exception so there should be some output to the terminal given that the driver doesn't catch it.

If you don't see anything you could try changing the updateTasks function in the spot wrapper to look like the below (untested code) and see if that will give you some output.

```
    def updateTasks(self):
        """Loop through all periodic tasks and update their data if needed."""
        try:
            self._async_tasks.update()
        except Exception as e:
            print(f"Update tasks failed with error: {str(e)}")
```

**Comment by civerachb-cpr** [comment]
Are you still having this problem, or were you able to get it resolved?

**Comment by civerachb-cpr** [comment]
Closing this due to inactivity.  Please leave a comment if you're still having this issue.
